### PR TITLE
feature: slack notify workflows; build-container and build-helm-package actions

### PR DESCRIPTION
**Pull request by kbeckman**
## [12/08/2022]

* `slack-notification-workflow-invoked.yml`
  * Workflow introduced to notify corporate Slack `#development` channel of invoked workflow events.
* `slack-notification-workflow-finished.yml`
  * Workflow introduced to notify corporate Slack `#development` channel of finished workflow events.
* `action/build-container`
  * Action introduced to build container images and (if caller opts-in) pushes the image to ECR.
* `action/build-helm-package`
  * Action introduced to build Helm chart packages and publish to the corporate Helm chart registry.

### CODE REVIEW

**Comment by jkleinknox** [comment]
On failure, is it possible to perform the slack notification with a `mention` of whoever's PR broke the build? I have the deployment channel muted, but it can still make someone aware with a `mention`. I've had it muted and changed it to just `mention`, so sorry if already does this.

**Comment by kbeckman** [comment]
> On failure, is it possible to perform the slack notification with a `mention` of whoever's PR broke the build? I have the deployment channel muted, but it can still make someone aware with a `mention`. I've had it muted and changed it to just `mention`, so sorry if already does this.

@jkleinknox -- at this point, it does not... It's not able to handle a cancelled workflow properly either (which I've created a ticket for). For the workflow related changes, I factored them out as inline steps (in the `sandbox-ui` PR workflow) and moved them to workflows so they could be used as bookend notifications for a workflow. IDK if the underlying GHA action it uses is capable of indicating who triggered the workflow. I agree with you though, that's important information. I just made sure I supported existing functionality first before adding any more. For the `sandbox-ui` project, we're just having to use the GitHub email notification to notify the triggering developer of any workflow failures.

**Comment by kbeckman** [comment]
image
Here's what the difference looks like between notifications for `core` and `sandbox-ui`... I'll add a story to make sure developer name or GitHub handle makes it into the Slack notification.

**Comment by kbeckman** [comment]
FYI - new story for developer name...
https://github.com/knox-networks/github-actions/issues/6

**Review by jkleinknox — APPROVED** [review]

**Comment by kbeckman** [comment]
> I really like the `README.md`s

👍 - might as well make it production/distribution-ready from the start...

**Pull request merged**
